-- 코드를 입력하세요
SELECT  F.FLAVOR
FROM FIRST_HALF AS F
JOIN 
(SELECT J.SHIPMENT_ID,J.FLAVOR,sum(J.TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY as J
GROUP BY FLAVOR) AS J
ON F.FLAVOR = J.FLAVOR 
ORDER BY F.TOTAL_ORDER+J.TOTAL_ORDER  DESC
LIMIT 3