-- 코드를 작성해주세요
WITH RankedFish AS (
    SELECT a.ID, b.FISH_NAME, a.FISH_TYPE, a.LENGTH,
           ROW_NUMBER() OVER (PARTITION BY a.FISH_TYPE ORDER BY a.LENGTH DESC) as rn
    FROM FISH_INFO a 
    JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM RankedFish
WHERE rn = 1
ORDER BY ID;
